export const K_TYPE = {
  NORMAL: '노말',
  FIRE: '불꽃',
  WATER: '물',
  GRASS: '풀',
  ELECTRIC: '전기',
  FIGHTING: '격투',
  FLYING: '비행',
  POISON: '독',
  GROUND: '땅',
  ROCK: '바위',
  BUG: '벌레',
  GHOST: '고스트',
  STEEL: '강철',
  PSYCHIC: '에스퍼',
  ICE: '얼음',
  DRAGON: '드래곤',
  DARK: '악',
  FAIRY: '페어리',
};
